name: minishell

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run executable
      run: |
        echo '
        spawn ./minishell
        expect "minishell>"
        send "echo Hello, world!\r"
        expect "minishell>"
        send "exit\r"
        expect eof
        ' > test_minishell.exp
        expect -f test_minishell.exp
